usr/lib/libsitter.so.*
usr/bin
usr/sbin
conf/sitter.conf                                etc/sitter/
conf/README.md                                  etc/sitter/sitter.d/
conf/logger/sitter.conf                         etc/sitter/logger/
conf/log-definitions/sitter.conf                usr/share/sitter/log-definitions/
conf/log-definitions/sitter-secure.conf         usr/share/sitter/log-definitions/
