usr/lib/libsitter.so.*
usr/lib/sitter
usr/bin
usr/sbin
usr/share/communicatord
usr/share/fluid-settings
usr/share/sitter
usr/share/snaplogger

conf/logger/README.md                           etc/sitter/logger/sitter.d/
conf/README.md                                  etc/sitter/sitter.d/

# we already install this one in usr/share/sitter
#conf/sitter.conf                                etc/sitter/
